//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADMINISTRADOR()
        {
            this.ENCARGADO = new HashSet<ENCARGADO>();
        }
    
        public int Identificacion_admin { get; set; }
        public string Nombre_admin { get; set; }
        public string Apellido_admin { get; set; }
        public string Correo_admin { get; set; }
        public string Tel_admin_admin { get; set; }
        public string Cargo_admin { get; set; }
        public string Pass_admin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENCARGADO> ENCARGADO { get; set; }
    }
}
