//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class APRENDIZ
    {
        public int Identificacion_aprendiz { get; set; }
        public string Tipo_documento { get; set; }
        public string Nombre_aprendiz { get; set; }
        public string Genero_aprendiz { get; set; }
        public string Ficha_aprendiz { get; set; }
        public string Modalidad_formacion { get; set; }
        public string Programa_formacion { get; set; }
        public string Jornada_formacion { get; set; }
        public string Nivel_formacion { get; set; }
        public string Centro_formacion { get; set; }
        public string Correo_aprendiz { get; set; }
        public string Telefono_aprendiz { get; set; }
        public int Identificacion_encargado { get; set; }
    
        public virtual ENCARGADO ENCARGADO { get; set; }
    }
}
