//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCARGADO
    {
        public int Identificacion_encargado { get; set; }
        public string Nombre_encargado { get; set; }
        public string Apellido_encargado { get; set; }
        public string Cargo_encargado { get; set; }
        public string Correo_encargado { get; set; }
        public string Telefono_encargado { get; set; }
        public string Pass_encargado { get; set; }
        public int Identificacion_admin { get; set; }
    
        public virtual ADMINISTRADOR ADMINISTRADOR { get; set; }
    }
}
