//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CIPREGISTER_MVCEntities : DbContext
    {
        public CIPREGISTER_MVCEntities()
            : base("name=CIPREGISTER_MVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRADOR> ADMINISTRADOR { get; set; }
        public virtual DbSet<ENCARGADO> ENCARGADO { get; set; }
        public virtual DbSet<ACTIVIDAD> ACTIVIDAD { get; set; }
        public virtual DbSet<ACTIVIDAD_HAS_APRENDIZ> ACTIVIDAD_HAS_APRENDIZ { get; set; }
        public virtual DbSet<APRENDIZ> APRENDIZ { get; set; }
        public virtual DbSet<REPORTE> REPORTE { get; set; }
    }
}
