//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTE
    {
        public int Cod_reporte { get; set; }
        public string fecha_reporte { get; set; }
        public Nullable<int> Cod_actividad { get; set; }
    
        public virtual ACTIVIDAD ACTIVIDAD { get; set; }
    }
}
